Repository Soongmile/Soongmile-FE, pull requests merged in 2023-08, with the labels that each got.

#12 [#10] Eslint 관련 버그 수정
  .eslintrc.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/mypage.tsx
  pages/search.tsx
  pages/signin.tsx
  pages/signup.tsx
  yarn.lock
Labels: Fix

#8 [#5] Text Input 컴포넌트 제작
  components/reusable/TextInput.tsx
  next.config.js
Labels: Feat

#11 [#6] 버튼 컴포넌트 제작
  assets/icons/Pencil.svg
  components/reusable/Buttons/CheckedBtn.tsx
  components/reusable/Buttons/QuestionBtn.tsx
  components/reusable/Buttons/SignoutBtn.tsx
  components/reusable/Buttons/UploadBtn.tsx
  next.config.js
  package.json
  yarn.lock
Labels: Feat

#14 [#2] 카드형 컴포넌트 수정사항
  components/reusable/Card.tsx
  components/reusable/Card/atoms/StackTagsWrap.tsx
  components/reusable/Card/index.tsx
  components/reusable/Tag.tsx
  hooks/useIsOverflow.ts
  hooks/useIsomorphicEffect.ts
  public/gradientLeft.svg
  public/gradientRight.svg
  public/leftArrow.svg
  public/rightArrow.svg
  styles/theme.tsx
Labels: Feat, Refactor

#15 [#4] 사이드바 컴포넌트
  components/reusable/SideBar.tsx
  components/reusable/SideBarList.tsx
  const/index.ts
  states/sideBarState.ts
Labels: Feat

#30 [#6] fix: onClick 타입 수정 및 예약어와 변수 중복 해결
  components/reusable/Buttons/CheckedBtn.tsx
  components/reusable/Buttons/SquareBtn.tsx
Labels: Fix

#31 Fix: 에러 스타일 버그 수정
  components/reusable/TextInput.tsx
Labels: Fix

#32 Etc: able 값에 맞춰서 스타일 적용
  components/reusable/Buttons/SquareBtn.tsx
Labels: Fix
